name: Docker Build and Push
on:
  push:
    branches: [main]

jobs:
  build-image:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Test Docker image
        run: |
          # Build the image
          docker build -t ${{ vars.DOCKERHUB_USERNAME }}/httpenv:latest .
          
          # Run the container
          docker run -d --name test-container -p 8888:8888 ${{ vars.DOCKERHUB_USERNAME }}/httpenv:latest
          
          # Test the container
          sleep 20  # Allow container to start
          curl -f http://localhost:8888
          
          # Stop and remove the container
          docker stop test-container
          docker rm test-container

      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        if: success()
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/httpenv:latest
